### ISSUE TITLE
bug: Publish summary only on commit.

### ISSUE THREAD

**Issue by dheerajdlalwani** [OurTechCommunity/catchup#42] opened 2022-04-06 10:42 UTC

**Comment by KartikSoneji** [comment] 2022-08-07 21:34
@dheerajdlalwani can you please provide some more details about the issue?
If possible, please include an example.

**Comment by HarshKapadia2** [comment] 2022-08-08 04:19
This was an issue that you had asked to be raised, @KartikSoneji. So both @dheerajdlalwani and you will have to try to remember the context.
If the context escapes both, one of y'all please close this issue.

PS: Was this to prevent publishing in the PR workflow? That was (finally) fixed in 5d8cd0788b428e2adad7c06e1af074da1c91aa46. If so, please close this issue.

**Comment by KartikSoneji** [comment] 2022-10-14 09:45
I can't remember what this issue was for, @dheerajdlalwani or @SirusCodes let me know if you do otherwise let's close this.

**Comment by SirusCodes** [comment] 2022-10-14 09:50
I'm totally out of loop of this issue. My wild guess would be to run action only if any summary or image is added or updated.

@dheerajdlalwani correct me if I'm wrong

**Comment by tusharnankani** [comment] 2022-10-16 16:49
> Publish summary only on commit

When else are we changing publishing it?

**Comment by SirusCodes** [comment] 2022-10-16 23:59
Closed this as context of the issue is lost.

**Closed** 2022-10-16 23:59 UTC
